### PR TITLE
Issue/0026

### PR DESCRIPTION
**Pull request by YoannBureau**
Updated Angular project from 6.0 to 7.1.3
Updated React project with the latest lib versions

### CODE REVIEW

**Comment by YoannBureau** [comment]
hello there

**Comment by lydiapuric** [comment]
@YoannBureau Thanks, we will have a look at it as soon as possible.

**Comment by pfauchere** [comment]
As on top of bumping the Angular version, the PR bumps the version of multiple other dependencies. It is worth ensuring we are not introducing any regression or security issues

**Comment by pfauchere** [comment]
Most importantly, we should consider bumping the version of Angular in the archetype now it is available. The journal will anyway be refreshed according to the archetype in a second phase

https://github.com/adobe/aem-spa-project-archetype/

**Comment by samuelmeuli** [comment]
@YoannBureau Thanks for opening the PR!

The [AEM Project Archetype](https://github.com/adobe/aem-project-archetype) can now generate Angular 8 projects. Please use that project as a reference.

**Pull request closed without merging**
